### PR TITLE
added support for placement groups

### PR DESCRIPTION
**Pull request by saschat**
Added support for placement groups by implementing the commands `CreatePlacementGroup` and `DescribePlacementGroups` and sending the placement group name with a `RunInstances` command.

### CODE REVIEW

**Comment by proger** [comment]
Thank you! Would you like a Hackage release right away?

**Comment by saschat** [comment]
Wow, that was fast!
You are welcome. A Hackage release would be nice, but not super urgent as I might also replace the `Value`s with per command response types for some of the commands. In case you are open to such changes, I am also happy with a Hackage release after that.

**Comment by proger** [comment]
Great, looking forward to it!

**Comment by saschat** [comment]
Could you do a Hackage release of this version? Thanks a lot!

**Pull request merged**
